export enum INTERESTS {
    EDUCATION_TECH = "EDUCATION_TECH",
    EDUCATION_BUSINESS = "EDUCATION_BUSINESS",
    EDUCATION_AI = "EDUCATION_AI",
    EMAIL_MARKETING = "EMAIL_MARKETING",
    DESIGN = "DESIGN",
    DISCOUNTS = "DISCOUNTS"
}

export enum CONTACT_ACTIONS {
    JOIN_SUMMON = "JOIN_SUMMON",
    LEFT_SUMMON = "LEFT_SUMMON",
    DOWNLOAD_ELEMENT = "DOWNLOAD_ELEMENT"
}

export enum UTILITY_TYPES {
    SUMMON = "SUMMON",
    DOWNLOAD = "DOWNLOAD"
}